export default {
  'url': 'URL',
  'tag': 'Tag',
  'name': 'Name',
  'add': 'Add',
  'addBookmark': 'Add bookmark',
  'addChannel': 'Add channel',
  'settings': 'Settings',
  'youtubeChannelOrPlaylist': 'Youtube channel or playlist',
  'empty': 'Empty',
  'noBookmarksFound': 'No bookmarks found',
  'noChannelsFound': 'No channels found',
  'noVideosFound': 'No videos found',
  'noConfigFound': 'No config found',
  'general': 'General',
  'channels': 'Channels',
  'bookmarks': 'Bookmarks',
  'remove': 'Remove',
  'restore': 'Restore',
  'instance': 'Instance',
  'instanceId': 'settings-instance',
  'saveHint': 'Press Enter to save changes',
  'notFound': 'Not found',
  'back': 'Back',
  'searchForChannel': 'Search for channel',
  'sync': 'Synchronize',
  'menu': 'Menu',
  pageNotFound: 'Page not found',
  all: 'All',
  allKebabCase: 'all',
  thumbnail: 'Thumbnail',
  imageFailed: 'Failed to load image',
  piped: 'Piped',
  feed: 'Feed',
  feedThumbnailThemed: 'Themed thumbnails',
  feedFetchAll: 'Fetch all videos (shorts, streams)',
  always: 'Always',
  minute: 'minute',
  minutes: 'minutes',
  feedCache: 'Reload after',
  feedCacheKebabCase: 'feed-cache',
  feedLimit: 'Videos limit',
  feedLimitKebabCase: 'feed-limit',
  customProtocol: 'Custom protocol',
  openVideosInApp: 'Open videos in app',
  useInTitles: 'Use in titles',
  customProtocolName: 'App',
  paths: {
    home:      '/',
    settings:  '/settings',
    channels:  '/settings/channels',
    bookmarks: '/settings/bookmarks',
    notFound:  '/not-found'
  }
}
