export default {
  add: 'Add',
  addBookmark: 'Add bookmark',
  addChannel: 'Add channel',
  all: 'All',
  allKebabCase: 'all',
  always: 'Always',
  back: 'Back',
  backendType: 'Backend type',
  backendUrl: 'Backend URL',
  bookmarks: 'Bookmarks',
  channels: 'Channels',
  configManagement: 'Configuration',
  customProtocol: 'Custom protocol',
  customProtocolName: 'App',
  directThumbnails: 'Fetch thumbnails directly from youtube',
  empty: 'Empty',
  exportConfig: 'Export',
  feedCacheKebabCase: 'feed-cache',
  feedCache: 'Reload after',
  feed: 'Feed',
  feedFetchAll: 'Fetch all videos (shorts, streams)',
  feedLimitKebabCase: 'feed-limit',
  feedLimit: 'Videos limit',
  feedThumbnailThemed: 'Themed thumbnails',
  general: 'General',
  imageFailed: 'Failed to load image',
  importConfig: 'Import',
  importFailed: 'Failed to import config',
  instanceId: 'settings-instance',
  instance: 'Instance',
  menu: 'Menu',
  minute: 'minute',
  minutes: 'minutes',
  name: 'Name',
  noBookmarksFound: 'No bookmarks found',
  noChannelsFound: 'No channels found',
  noConfigFound: 'No config found',
  notFound: 'Not found',
  noVideosFound: 'No videos found',
  openVideosInApp: 'Open videos in app',
  pageNotFound: 'Page not found',
  piped: 'Piped',
  remove: 'Remove',
  restore: 'Restore',
  saveHint: 'Press Enter to save changes',
  searchForChannel: 'Search',
  settings: 'Settings',
  startpage: 'startpage',
  startpageBackend: 'Startpage API',
  sync: 'Synchronize',
  tag: 'Tag',
  thumbnail: 'Thumbnail',
  url: 'URL',
  useInTitles: 'Use in titles',
  youtubeChannelOrPlaylist: 'Youtube channel or playlist',
  paths: {
    bookmarks: '/settings/bookmarks',
    channels: '/settings/channels',
    home: '/',
    notFound: '/not-found',
    settings: '/settings'
  }
}
